### ISSUE TITLE
add-on config 'startup', 'auto_uart' are deprecated.

### ISSUE THREAD

**Issue by joaudfo** [miumida/connector4hassio#1]
시스템 로그에 아래와 같은 경고 문구가 생겼습니다.
config에서 startup 값으로 before를 사용하는데 더이상 사용하지 않는 것 같네요. auto_uart는 uart로 변경되나 봅니다.
확인 부탁 드려요.

현재 사용 중인 core, supervisor 버전은 아래와 같습니다.
![image](https://user-images.githubusercontent.com/39111441/108473144-fdb20b00-72d0-11eb-8a69-6fc56c23d110.png)

21-02-19 05:20:38 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of Gh-Connector-rasp
21-02-19 05:20:38 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Gh-Connector-rasp
21-02-19 05:20:38 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of Gh-Connector New
21-02-19 05:20:38 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Gh-Connector New
21-02-19 05:20:38 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of Lg-Connector-rasp
21-02-19 05:20:38 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Lg-Connector-rasp
21-02-19 05:20:38 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of Gh-Connector
21-02-19 05:20:38 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Gh-Connector
21-02-19 05:20:38 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of Lg-Connector
21-02-19 05:20:38 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Lg-Connector
21-02-19 05:20:38 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of Mi-Connector
21-02-19 05:20:38 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Mi-Connector
21-02-19 05:20:38 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of Mi-Connector-arm
21-02-19 05:20:38 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Mi-Connector-arm

**Comment by miumida** [comment]
auto_uart -> uart
startup -> before
